// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartScheduler.Infrastructure.Data;

#nullable disable

namespace SmartScheduler.Infrastructure.Migrations
{
    [DbContext(typeof(SmartSchedulerDbContext))]
    [Migration("20251112212143_AddContractorEntity")]
    partial class AddContractorEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartScheduler.Domain.Contracts.Entities.Contractor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxJobsPerDay")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Skills");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Contractors", (string)null);
                });

            modelBuilder.Entity("SmartScheduler.Domain.Contracts.Entities.Contractor", b =>
                {
                    b.OwnsOne("SmartScheduler.Domain.Contracts.ValueObjects.ContractorCalendar", "Calendar", b1 =>
                        {
                            b1.Property<Guid>("ContractorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DailyBreakMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("Calendar_DailyBreakMinutes");

                            b1.Property<string>("Exceptions")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Calendar_Exceptions");

                            b1.Property<string>("Holidays")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Calendar_Holidays");

                            b1.HasKey("ContractorId");

                            b1.ToTable("Contractors");

                            b1.WithOwner()
                                .HasForeignKey("ContractorId");
                        });

                    b.OwnsOne("SmartScheduler.Domain.Contracts.ValueObjects.GeoLocation", "BaseLocation", b1 =>
                        {
                            b1.Property<Guid>("ContractorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("BaseLocation_Address");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("BaseLocation_City");

                            b1.Property<string>("Country")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("BaseLocation_Country");

                            b1.Property<string>("FormattedAddress")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("BaseLocation_FormattedAddress");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("BaseLocation_Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("BaseLocation_Longitude");

                            b1.Property<string>("PlaceId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("BaseLocation_PlaceId");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("BaseLocation_PostalCode");

                            b1.Property<string>("State")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("BaseLocation_State");

                            b1.HasKey("ContractorId");

                            b1.ToTable("Contractors");

                            b1.WithOwner()
                                .HasForeignKey("ContractorId");
                        });

                    b.OwnsMany("SmartScheduler.Domain.Contracts.ValueObjects.WorkingHours", "_workingHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ContractorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("integer");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("EndTime");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("StartTime");

                            b1.Property<string>("TimeZone")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TimeZone");

                            b1.HasKey("Id", "ContractorId");

                            b1.HasIndex("ContractorId");

                            b1.ToTable("ContractorWorkingHours", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ContractorId");
                        });

                    b.Navigation("BaseLocation")
                        .IsRequired();

                    b.Navigation("Calendar");

                    b.Navigation("_workingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
